---
- include_tasks: setup-Debian.yml

- name: Install Elasticsearch.
  package:
    name: elasticsearch
    state: "{{ elasticsearch_package_state }}"

- name: Configure Elasticsearch.
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0660

- name: modify the soft memlock limits.
  lineinfile:
    path: /etc/security/limits.conf
    line: '* soft memlock unlimited'

- name: modify the hard memlock limits.
  lineinfile:
    path: /etc/security/limits.conf
    line: '* hard memlock unlimited'

